kind: "AppHostingYaml"
apiVersion: "v1beta"
runConfig:
  basePath: "/"
env:
  - variable: NEXT_PUBLIC_FIREBASE_API_KEY
    value: "AIzaSyB_gMJYVUbDKgF0voTLQdr_3aIZYpjeRpk"
  - variable: NEXT_PUBLIC_FIREBASE_APP_ID
    value: "1:692364525603:web:beac187de76505dde0f196"
  - variable: NEXT_PUBLIC_API_URL
    value: "${NEXT_PUBLIC_API_URL:-http://localhost:8000}"
  - variable: NEXT_PUBLIC_KERNEL_HOST
    value: "localhost"
  - variable: NEXT_PUBLIC_KERNEL_PORT
    value: "9090"
