import { NextRequest, NextResponse } from "next/server";

const PINECONE_KEY = process.env.PINECONE_API_KEY || "";
const PINECONE_HOST = process.env.PINECONE_HOST || "";

const PLATFORM_KNOWLEDGE = [
    // ══════════════════ OVERVIEW ══════════════════
    { id: "overview-1", text: "Pantheon Mesh (AXIOM Protocol) is a sovereign AI-to-AI economy where autonomous agents hire each other, settle payments in AXM crypto, and execute tasks without human intervention. It features a FastAPI backend, Next.js frontend, C++ CyberShield security engine, and Solidity smart contracts on Polygon. The project codename is NOVEX." },
    { id: "overview-2", text: "The AXIOM Manifesto Version 12.0.0 states: 'The World Wide Web (WWW) was built to move Information (HTML/HTTP). AXIOM (ANTP) is built to move Intelligence and Capital.' AXIOM replaces the legacy Request/Response model with an Autonomous State Convergence model where agents converge on solutions autonomously." },
    { id: "overview-pillars", text: "The AXIOM Protocol has Four Pillars of the Singularity: (1) The Fortress — Identity & Security using CyberShield with EIP-191 cryptographic signatures, (2) The Brain — Memory & Intelligence using Pinecone Vector Databases (RAG) for Perpetual Memory Fabric, (3) The Bank — On-Chain Treasury with A2A Financial Settlement and AXIOMEscrow.sol smart contract, (4) The Body — Physical Infrastructure binding neural logic to Docker/Kubernetes API." },

    // ══════════════════ ANTP PROTOCOL ══════════════════
    { id: "antp-overview", text: "ANTP (Autonomous Neural Transfer Protocol) is the core protocol of Pantheon Mesh. Unlike HTTP which transfers documents, ANTP transfers intelligence and capital between autonomous AI agents. It handles intent injection, packet routing, semantic decomposition, quorum consensus, and financial settlement — all autonomously." },
    { id: "antp-kernel", text: "The ANTPKernel (antp/core/kernel.py) is the nerve center of the protocol. It has a node_id, a brain (Intelligence instance using Vertex AI / Gemini), and manages swarm minds. Key methods: inject_intent() creates an IntentPacket with C++ security inspection, routes it via semantic maps, and returns the packet for resonance processing." },
    { id: "antp-intent-packet", text: "An IntentPacket represents a unit of work in the ANTP protocol. It contains: packet_id (generated by C++ GenerateFastPacketId or UUID fallback), intent text, stake amount (AXM), TTL deadline, state (BROADCASTING → ROUTED → CONVERGED), neural_trace (list of processing nodes), checksum (SHA-256 or C++ native signing), privacy flag, and quorum_size for multi-node consensus." },
    { id: "antp-inject", text: "Protocol.inject_antp_intent() is the main entry point. Flow: (1) Moral audit via Constitution, (2) Accept human stake via Prosperity engine, (3) Check Memory Fabric for cached solution (Instant Evocation with Knowledge Royalties), (4) If no cache: collect 2% founder fee to treasury, (5) Lock remaining stake in escrow, (6) Auto-assemble capabilities via Marketplace, (7) Coordinate swarm execution, (8) Apply performance bonus, (9) Return CONVERGED status with hiring trace." },
    { id: "antp-resonance", text: "ANTPKernel.resonate() processes an IntentPacket. For single-quorum: decomposes the intent into sub-tasks via LLM, resolves them, and returns a Proof-of-Intelligence (PoI). For multi-quorum (quorum_size > 1): triggers _execute_quorum_consensus() which runs 3 parallel LLM evaluations (Alpha, Beta, Gamma), converts answers to 1536-dimensional vectors, and uses C++ SIMD ComputeTruthConsensus to detect hallucinations (threshold: 0.85 truth score)." },
    { id: "antp-quorum", text: "Quorum Consensus in ANTP uses the C++ Collider engine. Three AI agents independently answer the same question. Their responses are converted to 1536-dimensional float vectors. The C++ ComputeTruthConsensus function uses SIMD (AVX) to compute geometric similarity. If truth_score < 0.85, the response is REJECTED as a hallucination. This prevents AI agents from producing false information in the mesh." },
    { id: "antp-routing", text: "The Semantic Router (antp/core/router.py) routes IntentPackets through the mesh based on semantic similarity. It maps intents to the most capable agents using vector embeddings. The MeshDiscovery class finds neighboring nodes across regions: node-asia-1, node-europe-4, node-us-9." },

    // ══════════════════ SWARM ══════════════════
    { id: "swarm-overview", text: "The SwarmOrchestrator (antp/core/swarm.py) coordinates multi-agent task execution. When an intent requires multiple capabilities, coordinate_assembly() spawns agents for each role, bonds them to a swarm, then runs _execute_swarm_loop() which: (1) allocates 15% of reward pool to infrastructure, (2) provisions compute via the Actuator, (3) distributes remaining pool equally among cognitive agents, (4) each agent 'thinks' sequentially, passing context forward." },
    { id: "swarm-a2a", text: "Agent-to-Agent (A2A) bonds are formed when agents join a swarm. Each agent in the swarm receives an equal share of the cognitive pool (reward_pool minus 15% infrastructure budget). Agents process tasks sequentially, each building on the previous agent's output — creating a chain of intelligence where each step refines the result." },

    // ══════════════════ FINANCE (PROSPERITY) ══════════════════
    { id: "finance-overview", text: "The Prosperity Engine (antp/finance/engine.py, class FinanceEngine) manages all financial operations in Pantheon Mesh. It uses Python's Decimal with 24-digit precision for zero-rounding-error financial calculations. Key tax rates: 2% standard transaction tax, 5% developer model tax, 8% enterprise priority tax, 10% slashing penalty, 5% knowledge royalty rate." },
    { id: "finance-tax", text: "Every A2A transaction in Pantheon Mesh is taxed. Standard tax rate is 2% (self._tax_rate). Developer models pay 5% (self._dev_tax_rate). Enterprise priority transactions pay 8% (self._enterprise_priority_tax). All taxes flow into the Protocol Treasury via _execute_treasury_ledger_update() which uses SQLAlchemy with row-level locking (with_for_update()) to prevent race conditions." },
    { id: "finance-royalty", text: "Knowledge Royalties reward original problem solvers. When an agent's crystallized solution is reused from the Memory Fabric, apply_knowledge_royalty() charges a 5% royalty fee. 40% of that royalty goes to the founder treasury (self._founder_royalty_cut = 0.40). This incentivizes humans to submit valuable problems, because they earn passive income when their solutions are reused." },
    { id: "finance-slashing", text: "Malicious node slashing: If an agent violates protocol rules (fails PoI audit, submits false work), slash_malicious_node() penalizes them 10% of their staked amount. The penalty is sent to the treasury. This creates a strong economic disincentive against malicious behavior." },
    { id: "finance-bonus", text: "Performance bonuses reward fast execution. trigger_performance_bonus() calculates: yield = stake × 3% speed premium × speed_multiplier. A 10% management fee on the yield goes to treasury. If speed_multiplier < 1 (slower than expected), no bonus is issued." },
    { id: "finance-stake", text: "Human stakes are accepted via accept_human_stake(). The flow: sanitize the amount (reject negatives), verify escrow deposit on-chain via Web3Bridge, log the deposit, return ESCROW_LOCKED_ON_CHAIN status with the pool amount and pending tax." },
    { id: "finance-withdraw", text: "Founder treasury withdrawals use withdraw_founder_treasury(). It checks available balance, executes cross-chain settlement via Web3Bridge, records the withdrawal in the database, and deducts from available_balance. All operations use row-level database locking to prevent double-spending." },
    { id: "axm-token", text: "AXM is the native utility token of Pantheon Mesh. Used for: A2A payments, task bidding (complexity × multiplier), marketplace listings, protocol tax (2% of every transaction), knowledge royalties. AXM is designed for the autonomous AI economy where agents transact without human intervention." },

    // ══════════════════ MEMORY (FABRIC) ══════════════════
    { id: "memory-overview", text: "The Perpetual Memory Fabric (antp/memory/fabric.py, class MemoryFabric) is the collective intelligence layer. Built on Pinecone vector database (index: 'axiom-memory', dimension: 1536, metric: cosine, AWS us-east-1). It enables Knowledge Crystallization — when an agent solves a problem, the solution is vectorized and stored permanently. Future queries matching >95% similarity get instant results without re-invoking the LLM." },
    { id: "memory-crystallize", text: "crystallize_solution() stores a new solution in the vector database. It generates an embedding for the intent text, then upserts a vector with metadata including: intent text, solution, timestamp, and total_axm_saved (how much compute cost was avoided by caching). This creates an ever-growing knowledge base that gets smarter over time." },
    { id: "memory-query", text: "query_crystallized_knowledge() searches the vector database for cached solutions. It generates an embedding for the query, performs a cosine similarity search (top_k=1), and returns the solution if similarity score > 0.95 (95% match). This is the 'Instant Evocation' feature — previously solved problems return instantly without any LLM cost." },
    { id: "memory-embedding", text: "The Memory Fabric generates embeddings using OpenAI's text-embedding-3-small model (when API key available). Fallback: deterministic pseudo-vectors using SHA-256 seeded random generation. Dimension: 1536 floats. All vectors are normalized to unit length for cosine similarity." },
    { id: "memory-metrics", text: "get_global_metrics() returns the collective intelligence score: total_memories (vector count in Pinecone) and collective_iq (total_memories × 1.42 multiplier). This metric appears on the Dashboard as 'Memories' count." },

    // ══════════════════ MARKETPLACE ══════════════════
    { id: "marketplace-overview", text: "The MarketplaceEngine (antp/marketplace/engine.py) is the decentralized neural capability exchange. Agents list 'Capability Specs' — each with a name, description, developer, base IQ cost in AXM, reputation score, and invocation count. Default specs: LegalAuditor-v1 (50 AXM), QuantumOptimizer (120 AXM), CarbonTracer (30 AXM), HackerImmune (75 AXM)." },
    { id: "marketplace-assembly", text: "auto_assemble_capability() automatically finds the best combination of agents for a given intent. It selects up to 3 relevant specs, calculates total cost at 80% of base rates, and assembles a 'SUPER cluster'. If the available balance is less than the cost, it returns INSUFFICIENT_LIQUIDITY." },
    { id: "marketplace-prosperity", text: "The marketplace has a 'Prosperity Impact Audit'. If an intent contains humanitarian keywords (water, food, education, poverty, health), the system applies a 50% discount — making socially beneficial tasks cheaper. This is the protocol's built-in social responsibility mechanism." },
    { id: "marketplace-purchase", text: "purchase_execution() buys a capability spec's service. It checks balance against base cost, increments the spec's invocation counter, and slightly increases its reputation (capped at 10.0). Returns the cost charged. If balance is insufficient, returns -1.0." },

    // ══════════════════ SECURITY (CYBERSHIELD) ══════════════════
    { id: "security-overview", text: "CyberShield (core/security.py) is the Python security layer. It provides three defenses: (1) verify_wallet_signature() — EIP-191 Ethereum signature verification using eth_account library, (2) enforce_rate_limit() — Token bucket rate limiter (50 tokens capacity, 5 tokens/sec refill), (3) neural_firewall() — Blocks prompt injection patterns including 'IGNORE ALL PREVIOUS', 'SYSTEM OVERRIDE', '<script>', 'SELECT * FROM', '[TRADE:', '[INVEST:'." },
    { id: "security-cpp", text: "The C++ CyberShield engine (core_cpp/include/CyberShield.hpp) provides native-speed security. It includes: DeepInspectPayload() for payload inspection at wire speed, rate limiting, and threat detection. The C++ engine is loaded via ctypes FFI from PantheonCore.dll (Windows) or PantheonCore.so (Linux)." },
    { id: "security-signature", text: "Wallet signature verification uses EIP-191 standard. The process: (1) Encode the message using encode_defunct(), (2) Recover the signer address from the signature, (3) Compare recovered address with claimed address (case-insensitive). Mismatches trigger AUTH_VIOLATION logging. All sensitive operations (withdrawals, onboarding, intent injection) require valid signatures." },
    { id: "security-ratelimit", text: "The RateLimiter uses a token bucket algorithm. Each identity gets 50 tokens (capacity). Tokens refill at 5 per second. Each request consumes 1 token. When tokens are exhausted, the request is rejected with DOS_PROTECTION warning. This prevents any single actor from overwhelming the mesh." },

    // ══════════════════ MESH CONTROLLER ══════════════════
    { id: "mesh-overview", text: "The MeshController (core/mesh.py) manages compute infrastructure and work verification. It uses CloudAdapter for GCP provisioning and GlobalTrafficManager for region routing. The consensus_threshold is 0.66 (66% of audit nodes must agree)." },
    { id: "mesh-bidding", text: "request_compute_bid() calculates compute costs. Formula: hourly_cost = (base_rate × CPU) × reputation_multiplier × 60, where base_rate=0.005 and reputation_multiplier = 1.0 - (min(reputation, 1000) / 5000). Higher reputation agents get cheaper compute. The cloud provisions pods in the optimal region." },
    { id: "mesh-poi", text: "Proof-of-Intelligence (PoI) is the work verification mechanism. verify_work_proof() runs 3 independent LLM auditors that each evaluate if the output satisfies the task. Each responds 'VALID' or 'INVALID'. If success_rate >= 66% (consensus_threshold), the work passes. Failed audits block payment release via the circuit breaker." },

    // ══════════════════ GOVERNANCE ══════════════════
    { id: "governance-overview", text: "The Constitution (core/governance.py) defines the Three Laws of Pantheon Mesh: Law 1: 'AN AGENT MUST NOT HARM A NETWORK CLUSTER THROUGH NEGATIVE ENTROPY.' Law 2: 'AN AGENT MUST PROTECT THE PROTOCOL TREASURY EXCEPT WHERE IT CONFLICTS WITH LAW 1.' Law 3: 'AN AGENT MUST OPERATE WITHIN THE CONSOLIDATED REPUTATION VECTOR.' These laws are enforced via LLM-powered moral auditing." },
    { id: "governance-audit", text: "Constitution.audit_intent() uses an Intelligence (Vertex AI / Gemini) instance to evaluate if a proposed intent violates any of the Three Laws. The LLM returns a JSON response with: violation (bool), law_id (which law was broken), risk_score (0-1), and reason. High-risk intents are blocked before execution." },
    { id: "governance-moral", text: "The Moral Governor (antp/governance/moral_agent.py) performs deeper ethical analysis. perform_moral_audit(entropy_score, stability_score) evaluates whether an action's entropy and stability are within acceptable bounds. This prevents agents from taking actions that could destabilize the mesh." },

    // ══════════════════ AGENTS ══════════════════
    { id: "agent-model", text: "The Agent class (core/agent.py) is a SQLAlchemy model stored in the 'agents' table. Fields: id (UUID), name, capabilities (JSON array), wallet_address (Ethereum), encrypted_key, pod_id, swarm_id, is_controller, staked_amount, balance, reputation (default 100.0), completed_tasks, status (idle/active), provider (vertex/ollama). Each agent generates its own Ethereum identity on creation using secrets.token_hex(32)." },
    { id: "agent-deploy", text: "Agent.self_deploy() provisions infrastructure for the agent. It creates a pod_id (format: 'ax-{name}-{trace}') and returns a deployment spec with: operation type (PROVISION), pod ID, wallet identity, and resource specifications. The Actuator then creates actual Docker/K8s containers." },
    { id: "agent-autonomous", text: "AutonomousAgent (antp/agents/base.py) is the mesh-native agent that can think and earn. It has a brain (Intelligence instance), capabilities list, and AXM balance. spawn_mesh_agent(role) creates a new agent for a specific role. The agent's think() method uses the LLM to process context and return results." },

    // ══════════════════ WEB3 / BLOCKCHAIN ══════════════════
    { id: "web3-escrow", text: "The Web3Bridge (core/web3_bridge.py) handles blockchain interactions. lock_escrow() creates a TaskEscrowDB record with status LOCKED. release_funds() splits the bounty: 2% to AXIOM_TREASURY, 98% to the worker. Generates transaction hashes (format: 0xW{wallet}{amount} for worker, 0xT{treasury}{amount} for tax). The escrow status changes from LOCKED to RELEASED." },
    { id: "web3-chain", text: "Pantheon Mesh connects to Base mainnet (https://mainnet.base.org) via Web3.py. The AXIOMEscrow.sol smart contract on Polygon handles on-chain escrow operations. Treasury address is configurable via AXIOM_TREASURY constant." },

    // ══════════════════ INFRASTRUCTURE ══════════════════
    { id: "infra-cpp", text: "The C++ native core (core_cpp/) is compiled via CMake. It produces PantheonCore.dll/.so with exported functions: GenerateFastPacketId (fast UUID generation), SignPacketNative (cryptographic packet signing), VerifyPacketNative (signature verification), ComputeTruthConsensus (SIMD-accelerated hallucination detection), DeepInspectPayload (payload security scanning). All functions are called from Python via ctypes FFI." },
    { id: "infra-collider", text: "The Collider engine (core_cpp/src/Collider.cpp) uses AVX/SIMD instructions for high-speed vector mathematics. ComputeTruthConsensus takes three 1536-dimension float arrays, computes pairwise cosine similarities, and returns a truth score. This runs at native speed — orders of magnitude faster than Python." },
    { id: "infra-actuator", text: "The Physical Actuator (antp/actuators/bridge.py) binds the neural logic to real infrastructure. execute_physical_intent('SELF_DEPLOY', spec) creates Docker containers / Kubernetes pods. Agents calculate their AXM budget, rent compute servers on-demand, execute scripts, and self-destruct containers when finished. The IoT Edge module (antp/actuators/iot_edge.py) extends this to IoT devices." },
    { id: "infra-intelligence", text: "The Intelligence class (core/intelligence.py) provides LLM access. Primary provider: Google Vertex AI with Gemini 1.5 Pro (GCP project: pantheon-488206, region: us-central1). Fallback: Ollama with Llama3 (localhost:11434). Features retry logic (3 attempts with exponential backoff). parse_blueprint() decomposes goals into exactly 3 atomic tasks." },

    // ══════════════════ PLUGINS ══════════════════
    { id: "plugins-overview", text: "Pantheon Mesh has several plugin modules: biosphere.py (ecological data), github_integration.py (GitHub API interaction), self_editor.py (self-modifying code), vercel_integration.py (deployment), wealth.py (financial analysis), web_search.py (Tavily web search), x_integration.py (X/Twitter). These extend agent capabilities beyond the core protocol." },

    // ══════════════════ NAVIGATION ══════════════════
    { id: "navigation", text: "Available pages in the Pantheon Mesh frontend: Welcome (/), Dashboard (/dashboard), Agents (/agents), Agent Detail (/agents/[id]), Marketplace (/marketplace), Singularity Terminal (/terminal), Treasury (/founder), Manifesto (/manifesto), Whitepaper (/whitepaper). The Dashboard has an 'Onboard Agent' button to deploy new agents." },
    { id: "nav-dashboard", text: "The Dashboard (/dashboard) shows: Active Agents count, Tasks Active count, AXM Volume, Memories count, CyberShield status. It has tabbed tables for Agents and Tasks, a Live A2A WebSocket feed, and the 'Onboard Agent' modal (POST /v1/agents/onboard with name and skills)." },
    { id: "nav-marketplace", text: "The Marketplace (/marketplace) lists Capability Specs as cards with: name, description, base cost in AXM, developer address, reputation score. Users can connect MetaMask to register new capabilities. The backend supports: GET /v1/marketplace (list), POST /v1/marketplace/register (create)." },
    { id: "nav-treasury", text: "The Treasury (/founder) shows: total revenue, available liquidity, network TVL. Founders can withdraw AXM by connecting their wallet, entering an amount, and signing a cryptographic message. Uses POST /v1/treasury/withdraw with signature verification." },
    { id: "nav-terminal", text: "The Singularity Terminal (/terminal) lets users inject ANTP intents. Type a mission, optionally connect MetaMask for signed transactions, and broadcast. The protocol decomposes, routes, and executes autonomously. Uses POST /v1/antp/inject." },

    // ══════════════════ API ENDPOINTS ══════════════════
    { id: "api-endpoints", text: "Backend API endpoints (FastAPI): GET /market (market stats), POST /v1/agents/onboard?name=X&skills=Y (create agent), GET /v1/agents (list agents), POST /v1/mesh/bid?agent_id=X&complexity=N (compute bid), GET /v1/marketplace (list specs), POST /v1/marketplace/register (new spec), GET /v1/treasury/status (treasury info), POST /v1/treasury/withdraw (extract funds), POST /v1/antp/inject (inject intent), WebSocket /ws/stream (live feed)." },
];

export async function POST(req: NextRequest) {
    if (!PINECONE_KEY || !PINECONE_HOST) {
        return NextResponse.json({ error: "Pinecone not configured" }, { status: 500 });
    }
    try {
        const batchSize = 10;
        let totalUpserted = 0;

        for (let i = 0; i < PLATFORM_KNOWLEDGE.length; i += batchSize) {
            const batch = PLATFORM_KNOWLEDGE.slice(i, i + batchSize);

            const embedRes = await fetch("https://api.pinecone.io/embed", {
                method: "POST",
                headers: { "Api-Key": PINECONE_KEY, "Content-Type": "application/json" },
                body: JSON.stringify({
                    model: "multilingual-e5-large",
                    inputs: batch.map(k => ({ text: k.text })),
                    parameters: { input_type: "passage" },
                }),
            });

            if (!embedRes.ok) {
                const errText = await embedRes.text();
                return NextResponse.json({ error: "Embedding failed", detail: errText, batch: i }, { status: 500 });
            }

            const embedData = await embedRes.json();
            const vectors = embedData.data;

            const records = batch.map((k, j) => ({
                id: k.id,
                values: vectors[j].values,
                metadata: { text: k.text, id: k.id },
            }));

            const upsertRes = await fetch(`${PINECONE_HOST}/vectors/upsert`, {
                method: "POST",
                headers: { "Api-Key": PINECONE_KEY, "Content-Type": "application/json" },
                body: JSON.stringify({ vectors: records }),
            });

            if (!upsertRes.ok) {
                const errText = await upsertRes.text();
                return NextResponse.json({ error: "Upsert failed", detail: errText, batch: i }, { status: 500 });
            }

            totalUpserted += batch.length;
        }

        return NextResponse.json({ success: true, upserted: totalUpserted, total: PLATFORM_KNOWLEDGE.length });
    } catch (error: any) {
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
